### ISSUE TITLE
When no point lies inside bbox, program crashes

### ISSUE THREAD

**Issue by vbandaruk** [dengwirda/inpoly#3]
in inpoly2, pruning is done using bbox at line 108.
If mask is entirely false, i.e. all vert points are outside of bbox, then the program crashes as ddxy(1) and ddxy(2) (line 125) doesn't exist. 

Solution is to return from the function when vert(mask) is empty

**Comment by dengwirda** [comment]
Thanks @vbandaruk, I agree this looks like a bug to fix.

**Comment by dengwirda** [comment]
@vbandaruk, this should be fixed with the latest PR --- thanks for pointing this out!

**Comment by vbandaruk** [comment]
No problem. Glad to contribute. keep up your wonderful work 👍
