### ISSUE TITLE
Inaccurate Evaluation of points inside holed polygons

### ISSUE THREAD

**Issue by michelegatto1** [dengwirda/inpoly#6]
[Issue1.zip](https://github.com/dengwirda/inpoly/files/7466485/Issue1.zip)

I'm facing an issue trying to detect which of my query points, coming from a Digital Terrain Model, are inside the polygons of a lithological shapefile. Specifically, The issued polygon is holed and the attached image shows what happens (see lower part).

![figure1](https://user-images.githubusercontent.com/93647553/140037222-184dc564-e278-4e2e-ac2f-f2363340e241.png)

How could I solve it?

**Comment by dengwirda** [comment]
Hi @michelegatto1, I believe this is just a 'conventions' issue --- you look to be using a `NaN`-delimited polygon format (via `MATLAB`'s `polyshape`) but `inpoly` is based on the more general [`node-edge` topological layout](https://en.wikipedia.org/wiki/Planar_straight-line_graph). If you convert:
````
    % apparently saved in MATLAB's 'polyshape' format
    load 'Issue1/Issue1_polygon.mat'
    load 'Issue1/query_points.mat'

    % un-pack NaN-delimited polygons into topological
    % node-edge format for inpoly 
   [pp,ee] = getnan2(issue1_polygon.Vertices);
    
   [in,on] = inpoly2(query_points,pp,ee);
    
    figure;
    patch('faces',ee,'vertices',pp,'edgecolor','k','facecolor','w');
    axis equal; hold on;
    plot(query_points(in,1),query_points(in,2),'b.');
    plot(query_points(on,1),query_points(on,2),'r.');
````
where the `getnan2` can be found here: [https://github.com/dengwirda/mesh2d/blob/master/geom-util/getnan2.m](https://github.com/dengwirda/mesh2d/blob/master/geom-util/getnan2.m). You should get the expected output:

![issue_1](https://user-images.githubusercontent.com/10022384/140096241-afbc7408-2503-44a8-b301-4cb4dbaaa51a.jpg)

Adding the option to convert `NaN`-delimited inputs automatically within `inpoly` seems a reasonable improvement, so I've tagged this as an option for future releases.

**Comment by michelegatto1** [comment]
It's great! Now it works fine. Thanks a lot
