### ISSUE TITLE
Error encountered 

### ISSUE THREAD

**Issue by michelegatto1** [dengwirda/inpoly#7]
I got the following error applying "inpoly2" to the attached query points and polygon. How can I solve it?

_Index exceeds the number of array elements (0).

Error in inpoly2 (line 124)
    if (ddxy(1) > ddxy(2))_
[Issue 2.zip](https://github.com/dengwirda/inpoly/files/7466563/Issue.2.zip)

**Comment by dengwirda** [comment]
Hi @michelegatto1, I'm not able to reproduce this issue actually. Running with the current `inpoly/master` simply returns `in, on` all `false`. Is there something else I need to do?

**Comment by michelegatto1** [comment]
Actually, if I use "inpoly" it works. But with "inpoly2", it happens what I wrote...

**Comment by dengwirda** [comment]
@michelegatto1, it sounds like you may have a few different versions of `inpoly` installed? If so, could you double-check using the current `inpoly/master` branch --- there was a bug related to empty polygons that was [fixed](https://github.com/dengwirda/inpoly/pull/4) earlier this year (https://github.com/dengwirda/inpoly/pull/4) that may have addressed this.
